variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - test
  - package
  - publish

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: 
    - "mvn clean package -X"
  artifacts:
    paths:
      - target/*

sonarqube:
  stage: test
  only:
  - master
  needs: ["maven-build"]
  image: sonarsource/sonar-scanner-cli:latest
  allow_failure: true
  variables:
    SONAR_HOST_URL: https://sonar.sterul.com
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  script:
    - sonar-scanner 
      -Dsonar.qualitygate.wait=true 
      -Dsonar.sources=src 
      -Dsonar.login="$SONAR_TOKEN" 
      -Dsonar.projectKey="$CI_PROJECT_NAME" 
      -Dsonar.links.scm="$CI_PROJECT_URL" 
      -Dsonar.scm.revision="$CI_COMMIT_SHA" 
      -Dsonar.scm.disabled=False 
      -Dsonar.projectVersion="$CI_PIPELINE_IID"

package-docker-qa:
  stage: package
  needs: ["maven-build"]
  resource_group: qa
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    REGISTRY_TAG: qa
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$REGISTRY_TAG --cache=true --cache-ttl=100h
  only:
      - master

publish-cluster:
  stage: publish
  needs: ["package-docker-qa"]
  trigger:
    project: opencookbook/opencookbook-docker
    branch: main


# deploy_qa:
#   stage: publish
#   needs: ["package-docker-qa"]
#   resource_group: qa
#   image: registry.gitlab.com/gitlab-org/cluster-integration/helm-install-image/releases/2.16.6-kube-1.13.12
#   environment: 
#     name: qa
#   script: 
#     - kubectl get secret opencookbook-registry --namespace $KUBE_NAMESPACE && kubectl delete secret opencookbook-registry --namespace $KUBE_NAMESPACE
#     - kubectl create secret docker-registry opencookbook-registry --namespace $KUBE_NAMESPACE --docker-server=git.sterul.com:5005 --docker-username=$registry_user --docker-password=$registry_password
#     - kubectl get deployment opencookbook-qa --namespace $KUBE_NAMESPACE && kubectl delete deployment opencookbook-qa --namespace $KUBE_NAMESPACE
#     - kubectl apply -f kubernetes/deployment-qa.yml


#     # Wait for pod
#     - kubectl -n $KUBE_NAMESPACE wait --for=condition=available deployment/opencookbook-qa --timeout=300s


# stop-qa:
#   stage: deploy
#   script:
#     - 
#   environment:
#     name: qa
#     action: stop
#   rules: 
#     - if: $CI_MERGE_REQUEST_ID
#       when: manual
