-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated 
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
 BEGIN; 
 CREATE SEQUENCE IF NOT EXISTS public.hibernate_sequence
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE public.hibernate_sequence
    OWNER TO cookpal;
CREATE TABLE IF NOT EXISTS public.weekplan_day_recipe
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_simple_recipe boolean NOT NULL,
    simple_recipe_text character varying(255) COLLATE pg_catalog."default",
    recipe_id bigint,
    CONSTRAINT weekplan_day_recipe_pkey PRIMARY KEY (id),
    CONSTRAINT fk2kqhpe21rq75t9kbnyrjcdn20 FOREIGN KEY (recipe_id)
        REFERENCES public.recipe (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.weekplan_day_recipe
    OWNER to cookpal;
CREATE TABLE IF NOT EXISTS public.recipe
(
    id bigint NOT NULL,
    created_on timestamp without time zone,
    last_change timestamp without time zone,
    preparation_time bigint,
    recipe_type integer,
    servings integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default",
    total_time bigint,
    owner_user_id bigint,
    CONSTRAINT recipe_pkey PRIMARY KEY (id),
    CONSTRAINT fk1g5vb075llw7iebwhmpoqa0er FOREIGN KEY (owner_user_id)
        REFERENCES public.cookpal_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.recipe
    OWNER to cookpal;
CREATE TABLE IF NOT EXISTS public.recipe_needed_ingredients
(
    recipe_id bigint NOT NULL,
    needed_ingredients_id bigint NOT NULL,
    CONSTRAINT uk_ejfxae253m05jemfo5jmpdbda UNIQUE (needed_ingredients_id),
    CONSTRAINT fkj8rhgytyj93l46nneem8hmy8k FOREIGN KEY (needed_ingredients_id)
        REFERENCES public.ingredient_need (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fklwfbbwkluycv7kec66pwrc3m2 FOREIGN KEY (recipe_id)
        REFERENCES public.recipe (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.recipe_needed_ingredients
    OWNER to cookpal;
CREATE TABLE IF NOT EXISTS public.recipe_group
(
    id bigint NOT NULL,
    created_on timestamp without time zone,
    last_change timestamp without time zone,
    title character varying(255) COLLATE pg_catalog."default",
    owner_user_id bigint,
    CONSTRAINT recipe_group_pkey PRIMARY KEY (id),
    CONSTRAINT fkt6hs1xuh5560cx38cfqtknw8a FOREIGN KEY (owner_user_id)
        REFERENCES public.cookpal_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.recipe_group
    OWNER to cookpal;
CREATE TABLE IF NOT EXISTS public.recipe_preparation_steps
(
    recipe_id bigint NOT NULL,
    preparation_steps character varying(10000) COLLATE pg_catalog."default",
    CONSTRAINT fkj0e9vyqdwgq248e4ermdybfmj FOREIGN KEY (recipe_id)
        REFERENCES public.recipe (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.recipe_preparation_steps
    OWNER to cookpal;
CREATE TABLE IF NOT EXISTS public.recipe_image
(
    uuid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_on timestamp without time zone,
    last_change timestamp without time zone,
    owner_user_id bigint,
    CONSTRAINT recipe_image_pkey PRIMARY KEY (uuid),
    CONSTRAINT fkj76adcrs6u3mrdh859fr5ifh3 FOREIGN KEY (owner_user_id)
        REFERENCES public.cookpal_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.recipe_image
    OWNER to cookpal;
CREATE TABLE IF NOT EXISTS public.password_reset_link
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_on timestamp without time zone,
    last_change timestamp without time zone,
    valid_until timestamp without time zone,
    user_user_id bigint,
    CONSTRAINT password_reset_link_pkey PRIMARY KEY (id),
    CONSTRAINT fka1ixbid3v23p7girtl9v906pr FOREIGN KEY (user_user_id)
        REFERENCES public.cookpal_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.password_reset_link
    OWNER to cookpal;
CREATE TABLE IF NOT EXISTS public.recipe_recipe_groups
(
    recipe_id bigint NOT NULL,
    recipe_groups_id bigint NOT NULL,
    CONSTRAINT fkbub2c9bivmpscn16squ588thr FOREIGN KEY (recipe_groups_id)
        REFERENCES public.recipe_group (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkhvrwq8lq5ebj75hn2hel64m7t FOREIGN KEY (recipe_id)
        REFERENCES public.recipe (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.recipe_recipe_groups
    OWNER to cookpal;
CREATE TABLE IF NOT EXISTS public.refresh_token
(
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_on timestamp without time zone,
    last_change timestamp without time zone,
    valid_until timestamp without time zone,
    owner_user_id bigint,
    CONSTRAINT refresh_token_pkey PRIMARY KEY (token),
    CONSTRAINT fknrh9b93jfgfblg73evvi5y11t FOREIGN KEY (owner_user_id)
        REFERENCES public.cookpal_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.refresh_token
    OWNER to cookpal;
CREATE TABLE IF NOT EXISTS public.weekplan_day
(
    id bigint NOT NULL,
    created_on timestamp without time zone,
    last_change timestamp without time zone,
    day date,
    owner_user_id bigint,
    CONSTRAINT weekplan_day_pkey PRIMARY KEY (id),
    CONSTRAINT fkhokhwnamtv2fqfhebla8c7641 FOREIGN KEY (owner_user_id)
        REFERENCES public.cookpal_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.weekplan_day
    OWNER to cookpal;
CREATE TABLE IF NOT EXISTS public.cookpal_user
(
    user_id bigint NOT NULL,
    created_on timestamp without time zone,
    last_change timestamp without time zone,
    activated boolean NOT NULL,
    email_address character varying(255) COLLATE pg_catalog."default",
    password_hash character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT cookpal_user_pkey PRIMARY KEY (user_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.cookpal_user
    OWNER to cookpal;
CREATE TABLE IF NOT EXISTS public.activation_link
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_on timestamp without time zone,
    last_change timestamp without time zone,
    user_user_id bigint,
    CONSTRAINT activation_link_pkey PRIMARY KEY (id),
    CONSTRAINT fkdoritywxec5vjk5p4doifdns8 FOREIGN KEY (user_user_id)
        REFERENCES public.cookpal_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.activation_link
    OWNER to cookpal;
CREATE TABLE IF NOT EXISTS public.ingredient_need
(
    id bigint NOT NULL,
    created_on timestamp without time zone,
    last_change timestamp without time zone,
    amount real,
    unit character varying(255) COLLATE pg_catalog."default",
    ingredient_id bigint,
    CONSTRAINT ingredient_need_pkey PRIMARY KEY (id),
    CONSTRAINT fkhd47gqr4yl8ofcrs9gdhl2cto FOREIGN KEY (ingredient_id)
        REFERENCES public.ingredient (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.ingredient_need
    OWNER to cookpal;
CREATE TABLE IF NOT EXISTS public.recipe_images
(
    recipe_id bigint NOT NULL,
    images_uuid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT uk_612bgo9wf3fals5tin0cx1jo3 UNIQUE (images_uuid),
    CONSTRAINT fklk0yik8yjldhbq88btne0xl4b FOREIGN KEY (images_uuid)
        REFERENCES public.recipe_image (uuid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fks0cf53pdf5dn6mrf012xjv76c FOREIGN KEY (recipe_id)
        REFERENCES public.recipe (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.recipe_images
    OWNER to cookpal;
CREATE TABLE IF NOT EXISTS public.weekplan_day_recipes
(
    weekplan_day_id bigint NOT NULL,
    recipes_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT uk_90dl415qr2ln2rnu2tmlb9794 UNIQUE (recipes_id),
    CONSTRAINT fkfamh3p160eyoy7ftqsm4lepyp FOREIGN KEY (weekplan_day_id)
        REFERENCES public.weekplan_day (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkt547ywemycs27hb3cp27gfmc3 FOREIGN KEY (recipes_id)
        REFERENCES public.weekplan_day_recipe (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.weekplan_day_recipes
    OWNER to cookpal;
CREATE TABLE IF NOT EXISTS public.ingredient
(
    id bigint NOT NULL,
    created_on timestamp without time zone,
    last_change timestamp without time zone,
    is_public_ingredient boolean NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    owner_user_id bigint,
    CONSTRAINT ingredient_pkey PRIMARY KEY (id),
    CONSTRAINT fkj0har283erp1xjkqot3kssih5 FOREIGN KEY (owner_user_id)
        REFERENCES public.cookpal_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.ingredient
    OWNER to cookpal;

 END;