-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated 
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
 BEGIN; 

ALTER TABLE public.weekplan_day
    ALTER COLUMN created_on TYPE timestamp(6) with time zone ;

ALTER TABLE public.weekplan_day
    ALTER COLUMN last_change TYPE timestamp(6) with time zone ;

ALTER TABLE IF EXISTS public.weekplan_day_recipe
    ADD CONSTRAINT weekplan_day_recipe_recipe_id_key UNIQUE (recipe_id);

ALTER TABLE public.activation_link
    ALTER COLUMN created_on TYPE timestamp(6) with time zone ;

ALTER TABLE public.activation_link
    ALTER COLUMN last_change TYPE timestamp(6) with time zone ;

ALTER TABLE IF EXISTS public.activation_link
    ADD CONSTRAINT activation_link_user_user_id_key UNIQUE (user_user_id);

ALTER TABLE public.ingredient_need
    ALTER COLUMN created_on TYPE timestamp(6) with time zone ;

ALTER TABLE public.ingredient_need
    ALTER COLUMN last_change TYPE timestamp(6) with time zone ;

ALTER TABLE public.recipe_image
    ALTER COLUMN created_on TYPE timestamp(6) with time zone ;

ALTER TABLE public.recipe_image
    ALTER COLUMN last_change TYPE timestamp(6) with time zone ;

ALTER TABLE IF EXISTS public.recipe_images DROP CONSTRAINT IF EXISTS uk_612bgo9wf3fals5tin0cx1jo3;

ALTER TABLE IF EXISTS public.recipe_images
    ADD CONSTRAINT recipe_images_images_uuid_key UNIQUE (images_uuid);

ALTER TABLE IF EXISTS public.recipe_needed_ingredients DROP CONSTRAINT IF EXISTS uk_ejfxae253m05jemfo5jmpdbda;

ALTER TABLE IF EXISTS public.recipe_needed_ingredients
    ADD CONSTRAINT recipe_needed_ingredients_needed_ingredients_id_key UNIQUE (needed_ingredients_id);
ALTER TABLE public.refresh_token
    ALTER COLUMN created_on TYPE timestamp(6) with time zone ;

ALTER TABLE public.refresh_token
    ALTER COLUMN last_change TYPE timestamp(6) with time zone ;

ALTER TABLE public.refresh_token
    ALTER COLUMN valid_until TYPE timestamp(6) with time zone ;
ALTER TABLE public.password_reset_link
    ALTER COLUMN created_on TYPE timestamp(6) with time zone ;

ALTER TABLE public.password_reset_link
    ALTER COLUMN last_change TYPE timestamp(6) with time zone ;

ALTER TABLE public.password_reset_link
    ALTER COLUMN valid_until TYPE timestamp(6) without time zone ;
ALTER TABLE IF EXISTS public.password_reset_link
    ADD CONSTRAINT password_reset_link_user_user_id_key UNIQUE (user_user_id);

ALTER TABLE IF EXISTS public.weekplan_day_recipes DROP CONSTRAINT IF EXISTS uk_90dl415qr2ln2rnu2tmlb9794;

ALTER TABLE IF EXISTS public.weekplan_day_recipes
    ADD CONSTRAINT weekplan_day_recipes_recipes_id_key UNIQUE (recipes_id);
ALTER TABLE public.recipe
    ALTER COLUMN recipe_type TYPE smallint;

ALTER TABLE public.recipe
    ALTER COLUMN created_on TYPE timestamp(6) with time zone ;

ALTER TABLE public.recipe
    ALTER COLUMN last_change TYPE timestamp(6) with time zone ;

ALTER TABLE IF EXISTS public.recipe
    ADD CONSTRAINT recipe_recipe_type_check CHECK (recipe_type >= 0 AND recipe_type <= 2);
ALTER TABLE public.recipe_group
    ALTER COLUMN created_on TYPE timestamp(6) with time zone ;

ALTER TABLE public.recipe_group
    ALTER COLUMN last_change TYPE timestamp(6) with time zone ;
ALTER TABLE public.cookpal_user
    ALTER COLUMN created_on TYPE timestamp(6) with time zone ;

ALTER TABLE public.cookpal_user
    ALTER COLUMN last_change TYPE timestamp(6) with time zone ;

ALTER TABLE public.ingredient
    ALTER COLUMN created_on TYPE timestamp(6) with time zone ;

ALTER TABLE public.ingredient
    ALTER COLUMN last_change TYPE timestamp(6) with time zone ;

 END;