-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated 
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
 BEGIN; 
 CREATE TABLE IF NOT EXISTS public.ingredient_alternative_names
(
    created_on timestamp(6) with time zone,
    id bigint NOT NULL,
    ingredient_id bigint NOT NULL,
    last_change timestamp(6) with time zone,
    alternative_name character varying(255) COLLATE pg_catalog."default",
    language_iso_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ingredient_alternative_names_pkey PRIMARY KEY (id, ingredient_id, language_iso_code),
    CONSTRAINT fkamtnn0066o2q08mmyh5we82we FOREIGN KEY (ingredient_id)
        REFERENCES public.ingredient (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS public.ingredient_alternative_names
    OWNER to cookpal;

ALTER TABLE IF EXISTS public.ingredient
    ADD COLUMN alias_for_id bigint;

ALTER TABLE IF EXISTS public.ingredient
    ADD COLUMN nutrients_carbohydrates real;

ALTER TABLE IF EXISTS public.ingredient
    ADD COLUMN nutrients_energy real;

ALTER TABLE IF EXISTS public.ingredient
    ADD COLUMN nutrients_fat real;

ALTER TABLE IF EXISTS public.ingredient
    ADD COLUMN nutrients_protein real;

ALTER TABLE IF EXISTS public.ingredient
    ADD COLUMN nutrients_salt real;

ALTER TABLE IF EXISTS public.ingredient
    ADD COLUMN nutrients_saturated_fat real;

ALTER TABLE IF EXISTS public.ingredient
    ADD COLUMN nutrients_sugar real;

ALTER TABLE IF EXISTS public.ingredient
    ADD CONSTRAINT fkpksl6g80n423tap734mprav1v FOREIGN KEY (alias_for_id)
        REFERENCES public.ingredient (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


CREATE SEQUENCE IF NOT EXISTS public.ingredient_alternativenames_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

 END;